//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBU_Advising_Scheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbu_course_listing
    {
        public string Reporting_Term { get; set; }
        public string Term { get; set; }
        public string Course_Name { get; set; }
        public string Course { get; set; }
        public string Section { get; set; }
        public string Title { get; set; }
        public string Division_Desc { get; set; }
        public string Department { get; set; }
        public string Department_Description { get; set; }
        public string Current_Status { get; set; }
        public string Location { get; set; }
        public string Building { get; set; }
        public string Room { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public string Days { get; set; }
        public System.TimeSpan Start_Time { get; set; }
        public System.TimeSpan End_Time { get; set; }
        public int Section_Capacity { get; set; }
        public string Faculty_First_Name { get; set; }
        public string Faculty_Last_Name { get; set; }
        public string Notes { get; set; }
        public short Year { get; set; }
        public System.DateTime Start_Datetime { get; set; }
        public System.DateTime End_Datetime { get; set; }
    }
}
